namespace Cethleann.Structure
{
    public enum DataGame
    {
        None,
        DissidiaNT,
        DeadOrAlive5,
        DeadOrAlive6,
        Nioh,
        Nelke,
        Totori,
        Sophie,
        Meruru,
        Lydie,
        Lulua,
        Firis,
        Ryza,
        ThreeKingdomsXIV,
        Warriors7XL,
        Warriors8Empires,
        Warriors9,
        Scramble,
        DragonQuest,
        DragonQuest2,
        AttackOnTitan2,
        Hyrule,
        FireEmblemWarriors,
        ThreeHouses
    }
}
