using JetBrains.Annotations;

namespace Cethleann.Structure.DataStructs.DissidiaOO
{
    [PublicAPI]
    public struct AbilityInfo
    {
        public int Id { get; set; }
        public int Unknown1 { get; set; }
        public int Unknown2 { get; set; }
        public int Unknown3 { get; set; }
        public byte Unknown4 { get; set; }
        public bool UnknownFlag1 { get; set; }
        public bool UnknownFlag2 { get; set; }
        public byte Unknown5 { get; set; }
        public int Unknown6 { get; set; }
        public int Unknown7 { get; set; }
        public int Unknown8 { get; set; }
        public int Unknown9 { get; set; }
        public int UnknownA { get; set; }
        public int UnknownB { get; set; }
        public int UnknownC { get; set; }
        public int UnknownD { get; set; }
        public int UnknownE { get; set; }
        public int UnknownF { get; set; }
        public int Unknown10 { get; set; }
        public int Unknown11 { get; set; }
        public int Unknown12 { get; set; }
        public int Unknown13 { get; set; }
        public int Unknown14 { get; set; }
        public int Unknown15 { get; set; }
        public int Unknown16 { get; set; }
        public int Unknown17 { get; set; }
        public int Unknown18 { get; set; }
        public int Unknown19 { get; set; }
        public int Unknown1A { get; set; }
        public int Unknown1B { get; set; }
        public int Unknown1C { get; set; }
        public int Unknown1D { get; set; }
        public int Unknown1E { get; set; }
        public int Unknown1F { get; set; }
        public int Unknown20 { get; set; }
        public int Unknown21 { get; set; }
        public int Unknown22 { get; set; }
        public int Unknown23 { get; set; }
        public int Unknown24 { get; set; }
        public int Unknown25 { get; set; }
        public int Unknown26 { get; set; }
        public int Unknown27 { get; set; }
        public int Unknown28 { get; set; }
        public int Unknown29 { get; set; }
        public int Unknown2A { get; set; }
        public int Unknown2B { get; set; }
        public int Unknown2C { get; set; }
        public int Unknown2D { get; set; }
        public int Unknown2E { get; set; }
        public int Unknown2F { get; set; }
        public int Unknown30 { get; set; }
        public int Unknown31 { get; set; }
        public int Unknown32 { get; set; }
        public int Unknown33 { get; set; }
        public int Unknown34 { get; set; }
        public int Unknown35 { get; set; }
        public int Unknown36 { get; set; }
        public int Unknown37 { get; set; }
        public int Unknown38 { get; set; }
        public int Unknown39 { get; set; }
        public int Unknown3A { get; set; }
        public int Unknown3B { get; set; }
        public int Unknown3C { get; set; }
        public int Unknown3D { get; set; }
        public int Unknown3E { get; set; }
        public int Unknown3F { get; set; }
        public int Unknown40 { get; set; }
        public int Unknown41 { get; set; }
        public int Unknown42 { get; set; }
        public int Unknown43 { get; set; }
        public int Unknown44 { get; set; }
        public int Unknown45 { get; set; }
        public int Unknown46 { get; set; }
        public int Unknown47 { get; set; }
        public int Unknown48 { get; set; }
        public int Unknown49 { get; set; }
        public int Unknown4A { get; set; }
        public int Unknown4B { get; set; }
        public int Unknown4C { get; set; }
        public int Unknown4D { get; set; }
        public int Unknown4E { get; set; }
        public int Unknown4F { get; set; }
        public int Unknown50 { get; set; }
        public int Unknown51 { get; set; }
        public int Unknown52 { get; set; }
        public int Unknown53 { get; set; }
        public int Unknown54 { get; set; }
        public int Unknown55 { get; set; }
        public int Unknown56 { get; set; }
        public int Unknown57 { get; set; }
        public int Unknown58 { get; set; }
        public int Unknown59 { get; set; }
        public int Unknown5A { get; set; }
        public int Unknown5B { get; set; }
        public int Unknown5C { get; set; }
        public int Unknown5D { get; set; }
        public int Unknown5E { get; set; }
        public int Unknown5F { get; set; }
        public int Unknown60 { get; set; }
        public int Unknown61 { get; set; }
        public int Unknown62 { get; set; }
        public int Unknown63 { get; set; }
        public int Unknown64 { get; set; }
        public int Unknown65 { get; set; }
        public int Unknown66 { get; set; }
        public byte Unknown67 { get; set; }
        public string Name { get; set; }
        public string Single { get; set; }
        public string Pural { get; set; }
        public string Description { get; set; }
        public int Unknown6C { get; set; }
        public int Unknown6D { get; set; }
        public int Unknown6E { get; set; }
        public int Unknown6F { get; set; }
        public int Unknown70 { get; set; }
        public int Unknown71 { get; set; }
        public int Unknown72 { get; set; }
        public int Unknown73 { get; set; }
        public int Unknown74 { get; set; }
        public int Unknown75 { get; set; }
        public int Unknown76 { get; set; }
        public int Unknown77 { get; set; }
        public int Unknown78 { get; set; }
        public int Unknown79 { get; set; }
        public int Unknown7A { get; set; }
        public int Unknown7B { get; set; }
        public int Unknown7C { get; set; }
        public int Unknown7D { get; set; }
        public int Unknown7E { get; set; }
        public int Unknown7F { get; set; }
        public int Unknown80 { get; set; }
        public int Unknown81 { get; set; }
        public int Unknown82 { get; set; }
        public int Unknown83 { get; set; }
        public int Unknown84 { get; set; }
        public int Unknown85 { get; set; }
        public int Unknown86 { get; set; }
        public int Unknown87 { get; set; }
        public int Unknown88 { get; set; }
        public int Unknown89 { get; set; }
        public int Unknown8A { get; set; }
        public int Unknown8B { get; set; }
        public int Unknown8C { get; set; }
        public int Unknown8D { get; set; }
        public int Unknown8E { get; set; }
        public int Unknown8F { get; set; }
        public int Unknown90 { get; set; }
        public int Unknown91 { get; set; }
    }
}
